### ISSUE TITLE
Unable to revoke access to a device

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#439]
Problem reported by Chouffy (chouffy.cozycloud.cc): he has synchronized a smartphone with it's server and is unable to revoke access : the revocation seems to work, but after reloading the page, the device is still present.

**Comment by Chouffy** [comment]
I'll add that that the button change for a loading circle for ~1 sec (after confirmation), then goes back to "revoke device", but without the bin icon.

I've added a second device, and I'm unable to revoke it either.

**Comment by Chouffy** [comment]
For information : 
Data System: 2.0.4
Proxy: 2.0.0
Home: 2.0.2
Controller: 2.0.26

**Comment by Chouffy** [comment]
Log (redacted) : 

[Sat, 27 Jun 2015 11:45:01 GMT] - DELETE /api/devices/DEV_ID - 500 - 9.487 ms -  21
Error: Parsing error : Unexpected token C, body= 
 Cannot DELETE /device/DEV_ID/

    at parseBody (/usr/local/cozy/apps/home/node_modules/request-json/main.js:19:19)
    at Request._callback (/usr/local/cozy/apps/home/node_modules/request-json/main.js:124:18)
    at Request.self.callback (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)

**Comment by clochix** [comment]
@Chouffy: I tried to manually delete the device in database, can you try if you still see it ?

@poupotte we try to delete the device without providing a revision, so we get `{"error":"conflict","reason":"Document update conflict."}` which isn't well catch. I don't know if the error is in Home or CodyDB (ping @aenario ).

I successfully deleted the document with curl by adding its latest revision id.

**Comment by clochix** [comment]
@Chouffy by the way, thanks for this detailed report, it was helpful ☺

**Comment by Chouffy** [comment]
@clochix The device appear no more in the manager.
I'm still unable to revoke the other device, the log has recorded the same error (it's for the test, I don't want to delete it so don't worry about that).

**Comment by aenario** [comment]
@poupotte , could you take a look ?

It seems cozy-home call a now defunct route of the data-system. 

https://github.com/cozy/cozy-home/blob/4a818e928115b878764e1766cdb83b31117fb43b/server/controllers/devices.coffee#L26

**Comment by clochix** [comment]
Thanks @poupotte, it works fine now ☺
@Chouffy can you update your stack and try to remove your device ? It should have been fixed.

**Comment by Chouffy** [comment]
Hi,
I updated to : 
Data System: 2.0.5
Proxy: 2.0.1
Home: 2.0.3
Controller: 2.0.26

but the problem is still present & the same.

Here is the log :

```
[Wed, 01 Jul 2015 15:33:21 GMT] - GET /logs/home - 200 - 0.763 ms -  -
[Wed, 01 Jul 2015 15:33:34 GMT] - DELETE /api/devices/DEV_ID- 500 - 10.882 ms -  21
17)
    at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
Error: Parsing error : Unexpected token C, body= 
 Cannot DELETE /device/DEV_ID/

    at parseBody (/usr/local/cozy/apps/home/node_modules/request-json/main.js:19:19)
    at Request._callback (/usr/local/cozy/apps/home/node_modules/request-json/main.js:124:18)
    at Request.self.callback (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/home/node_modules/request-json/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

**Comment by clochix** [comment]
@poupotte another user is reporting the same problem [in forum](https://forum.cozy.io/t/bug-etats-mobiles-et-tablettes-revoquer-lappareil-ne-semble-pas-fonctionner/874). Could you have a look ?

**Comment by aenario** [comment]
My fault, it is merged into development, but not master & published :-/

**Comment by clochix** [comment]
Thanks @aenario (and @poupotte), users are reporting that it works now :-)
